#!/bin/bash

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_check_thorfile() {
  if [ ! thor tasks 2> /dev/null ]; then
    return
  fi

  local tasks=$(thor -T | grep -v "^\-\+\|Tasks" | awk '{{print $2}}' | grep -v -e '^$')
  local builtins=$(thor help | grep -v "^\-\+\|Tasks" | awk '{{print $2}}' | grep -v -e '^$')
  
  COMPREPLY=( $(compgen -W "${tasks} ${builtins}" -- $2) )
}
complete -F _check_thorfile -o default thor
